# @package _global_

defaults:
  - _self_
  - data: face # choose datamodule with `test_dataloader()` for evaluation
  - model: face
  - logger: null
  - trainer: face
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs\train\runs\2023-11-19_08-06-22\checkpoints\epoch_000.ckpt
